name: Go CI

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      
    - name: Install dependencies
      run: go get ./...

    - name: Lint
      uses: golangci/golangci-lint-action@v7
      with:
        version: v2.0

    - name: Test
      run: |
        go install github.com/onsi/ginkgo/v2/ginkgo
        ginkgo run -r -race -cover

    - name: Build
      run: go build -v ./...
